# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: cynoguard_tech_admin
      POSTGRES_DB: cynoguard
      POSTGRES_PASSWORD: cynoguard2026121
    ports:
      - "5448:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "9977:8080"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data  

volumes:
  pgdata:
  redisdata: